[2021-07-02 14:44:57,642] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fusemachines_Airflow_project.sucessful_category 2021-07-01T00:05:00+00:00 [queued]>
[2021-07-02 14:44:57,654] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fusemachines_Airflow_project.sucessful_category 2021-07-01T00:05:00+00:00 [queued]>
[2021-07-02 14:44:57,654] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:44:57,654] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-07-02 14:44:57,654] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:44:57,772] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): sucessful_category> on 2021-07-01T00:05:00+00:00
[2021-07-02 14:44:57,774] {standard_task_runner.py:52} INFO - Started process 66569 to run task
[2021-07-02 14:44:57,778] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fusemachines_Airflow_project', 'sucessful_category', '2021-07-01T00:05:00+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp371v1at6', '--error-file', '/tmp/tmphbia74qf']
[2021-07-02 14:44:57,779] {standard_task_runner.py:77} INFO - Job 122: Subtask sucessful_category
[2021-07-02 14:44:58,361] {logging_mixin.py:104} INFO - Running <TaskInstance: Fusemachines_Airflow_project.sucessful_category 2021-07-01T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-02 14:44:59,661] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fusemachines_Airflow_project
AIRFLOW_CTX_TASK_ID=sucessful_category
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:05:00+00:00
[2021-07-02 14:45:09,667] {taskinstance.py:866} INFO - Dependencies not met for <TaskInstance: Fusemachines_Airflow_project.sucessful_category 2021-07-01T00:05:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2021-07-02 14:45:09,668] {taskinstance.py:866} INFO - Dependencies not met for <TaskInstance: Fusemachines_Airflow_project.sucessful_category 2021-07-01T00:05:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-07-02 14:45:09,685] {local_task_job.py:98} INFO - Task is not able to be run
[2021-07-02 14:45:12,939] {python.py:151} INFO - Done. Returned value was: None
[2021-07-02 14:45:12,945] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fusemachines_Airflow_project, task_id=sucessful_category, execution_date=20210701T000500, start_date=20210702T085957, end_date=20210702T090012
[2021-07-02 14:45:13,363] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-02 14:45:13,386] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 66569
[2021-07-02 14:45:13,386] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-07-02 14:45:13,403] {process_utils.py:66} INFO - Process psutil.Process(pid=66569, status='terminated', exitcode=1, started='14:44:56') (66569) terminated with exit code 1
